### ISSUE TITLE
Add dark and light theme

### ISSUE THREAD

**Issue by aditya-singh9** [aditya-singh9/url-shotener-frontend-ts#16]
Add dark and light theme. The user can toggle the button and switch between them.

**Comment by codegoggins** [comment]
Hey !
This is my very first time contributing to open source. How exactly should I contribute to this project ? I am new to Open Source , it would be great if you could help. I would love to work on this feature

**Comment by aditya-singh9** [comment]
First you need to fork this repo into your account so that you can make changes to the code.
Remeber to keep syncing the fork to reduce conflicts.

Then you do all the changes in the code in the fork you made.

When you are done with adding features, you have to create a pull request(PR) from your fork to the main branch.

Then i will check your code and if it looks fine and has no conflicts with the base branch then i will merge the pull request and you are done!

If you have any issue doing these then you can just google them or watch some tutorials on youtube. It will help you a lot.

**Comment by aditya-singh9** [comment]
If you want to work on this issue, i will assign it to you. 
Let me know in the comment.

**Comment by codegoggins** [comment]
Thanks @aditya-singh9 
Yes I would love to work on this feature

**Comment by sambhavgupta0705** [comment]
Hey can I also work on this issue

**Comment by aditya-singh9** [comment]
The first person who creates adds the feature and creates a pull request will get the benefit of this pr in hactoberfest event.

**Comment by Anuran12** [comment]
Hi @aditya-singh9 can you assign it to me ?

**Comment by Onyelaudochukwuka** [comment]
I'll love to take this on 💪🏼

**Comment by DevilzzNikhil** [comment]
@aditya-singh9  can u assign it to me also

**Comment by atom540** [comment]
hey, I want to work on this topic because I make dark mode on the website in my project. so, can you assign this topic to me?

**Comment by Anshumansengar** [comment]
Hey, is the issue resolved? If not I would like to work on it.

**Comment by aditya-singh9** [comment]
I do not know why noone has create pr about this

**Comment by Anuran12** [comment]
> I do not know why noone has create pr about this

because you did not assign it to me :(

**Comment by Anuran12** [comment]
@aditya-singh9 I will do this real quick if you let me in

**Comment by ShivaRapolu01** [comment]
> The first person who creates adds the feature and creates a pull request will get the benefit of this pr in hactoberfest event.

In that case I would also like to give this a shot

**Comment by aditya-singh9** [comment]
Alright then
@ShivaRapolu01 and @Anuran12 are assigned to this issue and the one who creates the pull request first will get the benefit hacktoberfest, obviously the pr should not be spammy and i have to merge it

**Comment by Anuran12** [comment]
@aditya-singh9 Please check out my PR
