### ISSUE TITLE
Add number of stars and forks

### ISSUE THREAD

**Issue by aditya-singh9** [aditya-singh9/url-shotener-frontend-ts#18]
Add dynamic number of stars and number of forks on the website

![Example](https://user-images.githubusercontent.com/76763565/192849800-66dd2794-1dea-496a-9206-b3f7e04c161e.jpg)

**Comment by codewithpom** [comment]
Use the github api in the backend

**Comment by aditya-singh9** [comment]
Do you want to work on this?

**Comment by ShivaRapolu01** [comment]
I would like to work on this

**Comment by Anuran12** [comment]
hi @aditya-singh9 can you assign it to me ?

**Comment by ShivaRapolu01** [comment]
![Screenshot from 2022-09-30 17-27-06](https://user-images.githubusercontent.com/79957651/193264639-bad9299d-72fa-4a5f-87f3-822ffb96c9a8.png)
@aditya-singh9  I am getting this error after running npm install. In terminal it said that some version are outdated

**Comment by aditya-singh9** [comment]
I guess now it is fixed
