### ISSUE TITLE
Add a create another Shortened Link button

### ISSUE THREAD

**Issue by soustab10** [aditya-singh9/url-shotener-frontend-ts#22]
As per the current UI, to create another shortened link , user has to select the existing text, delete it and then paste the new link.
![image](https://user-images.githubusercontent.com/95632583/193428788-3e89b1d2-42c8-415e-8e6a-bf8a8040003b.png)
A button could be added to clear the link field, helping in user experience.
If approved, @aditya-singh9 I would like on this issue.

**Comment by codewithpom** [comment]
Assign me this issue

**Comment by sambhavgupta0705** [comment]
Hey can I work on this issue please

**Comment by aditya-singh9** [comment]
@soustab10 is already assigned to it.
Feel free to open a new issue about adding or fixing something else

**Comment by sambhavgupta0705** [comment]
ok
